// <auto-generated />
using System;
using Ivy.Open.Raise.Connections.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ivy.Open.Raise.Connections.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260106141540_OnboardingCompleted")]
    partial class OnboardingCompleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestorCountry", b =>
                {
                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.HasKey("InvestorId", "CountryId");

                    b.HasIndex(new[] { "CountryId" }, "IX_investor_countries_country_id");

                    b.ToTable("investor_countries", (string)null);
                });

            modelBuilder.Entity("InvestorStartupStage", b =>
                {
                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_id");

                    b.Property<int>("StartupStage")
                        .HasColumnType("integer")
                        .HasColumnName("startup_stage");

                    b.HasKey("InvestorId", "StartupStage");

                    b.HasIndex(new[] { "StartupStage" }, "IX_investor_startup_stages_startup_stage");

                    b.ToTable("investor_startup_stages", (string)null);
                });

            modelBuilder.Entity("InvestorStartupVertical", b =>
                {
                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_id");

                    b.Property<int>("StartupVerticalId")
                        .HasColumnType("integer")
                        .HasColumnName("startup_vertical_id");

                    b.HasKey("InvestorId", "StartupVerticalId");

                    b.HasIndex(new[] { "StartupVerticalId" }, "IX_investor_startup_verticals_startup_vertical_id");

                    b.ToTable("investor_startup_verticals", (string)null);
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("investor_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XUrl")
                        .HasColumnType("text")
                        .HasColumnName("x_url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvestorId" }, "IX_contacts_investor_id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AmountFrom")
                        .HasColumnType("integer")
                        .HasColumnName("amount_from");

                    b.Property<int?>("AmountTo")
                        .HasColumnType("integer")
                        .HasColumnName("amount_to");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DealApproachId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_approach_id");

                    b.Property<int>("DealStateId")
                        .HasColumnType("integer")
                        .HasColumnName("deal_state_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("NextAction")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action");

                    b.Property<string>("NextActionNotes")
                        .HasColumnType("text")
                        .HasColumnName("next_action_notes");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<float>("Order")
                        .HasColumnType("real")
                        .HasColumnName("order");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContactId" }, "IX_deals_contact_id");

                    b.HasIndex(new[] { "DealApproachId" }, "IX_deals_deal_approach_id");

                    b.HasIndex(new[] { "DealStateId" }, "IX_deals_deal_state_id");

                    b.HasIndex(new[] { "OwnerId" }, "IX_deals_owner_id");

                    b.ToTable("deals");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DealApproach", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("deal_approaches");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DealState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.ToTable("deal_states");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("decks");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContactId" }, "IX_deck_links_contact_id");

                    b.HasIndex(new[] { "DeckId" }, "IX_deck_links_deck_id");

                    b.ToTable("deck_links");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckLinkView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeckLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_link_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DeckLinkId" }, "IX_deck_link_views_deck_link_id");

                    b.ToTable("deck_link_views");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blob_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("deck_versions");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InteractionType")
                        .HasColumnType("integer")
                        .HasColumnName("interaction_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContactId" }, "IX_interactions_contact_id");

                    b.HasIndex(new[] { "InteractionType" }, "IX_interactions_interaction_type");

                    b.HasIndex(new[] { "UserId" }, "IX_interactions_user_id");

                    b.ToTable("interactions");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.InteractionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("interaction_types");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressCity")
                        .HasColumnType("text")
                        .HasColumnName("address_city");

                    b.Property<int?>("AddressCountryId")
                        .HasColumnType("integer")
                        .HasColumnName("address_country_id");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("text")
                        .HasColumnName("address_street");

                    b.Property<string>("AddressZip")
                        .HasColumnType("text")
                        .HasColumnName("address_zip");

                    b.Property<int?>("CheckSizeMax")
                        .HasColumnType("integer")
                        .HasColumnName("check_size_max");

                    b.Property<int?>("CheckSizeMin")
                        .HasColumnType("integer")
                        .HasColumnName("check_size_min");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InvestorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("investor_type_id");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Thesis")
                        .HasColumnType("text")
                        .HasColumnName("thesis");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.Property<string>("XUrl")
                        .HasColumnType("text")
                        .HasColumnName("x_url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressCountryId" }, "IX_investors_address_country_id");

                    b.HasIndex(new[] { "InvestorTypeId" }, "IX_investors_investor_type_id");

                    b.ToTable("investors");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.InvestorType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("investor_types");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.OrganizationSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Cofounders")
                        .HasColumnType("integer")
                        .HasColumnName("cofounders");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_id")
                        .IsFixedLength();

                    b.Property<string>("ElevatorPitch")
                        .HasColumnType("text")
                        .HasColumnName("elevator_pitch");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("OutreachBody")
                        .HasColumnType("text")
                        .HasColumnName("outreach_body");

                    b.Property<string>("OutreachSubject")
                        .HasColumnType("text")
                        .HasColumnName("outreach_subject");

                    b.Property<int?>("RaiseTargetMax")
                        .HasColumnType("integer")
                        .HasColumnName("raise_target_max");

                    b.Property<int?>("RaiseTargetMin")
                        .HasColumnType("integer")
                        .HasColumnName("raise_target_min");

                    b.Property<int?>("RaiseTicketSize")
                        .HasColumnType("integer")
                        .HasColumnName("raise_ticket_size");

                    b.Property<DateTime?>("StartupDateOfIncorporation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startup_date_of_incorporation");

                    b.Property<string>("StartupGovId")
                        .HasColumnType("text")
                        .HasColumnName("startup_gov_id");

                    b.Property<string>("StartupLinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("startup_linkedin_url");

                    b.Property<string>("StartupName")
                        .HasColumnType("text")
                        .HasColumnName("startup_name");

                    b.Property<int>("StartupStageId")
                        .HasColumnType("integer")
                        .HasColumnName("startup_stage_id");

                    b.Property<string>("StartupWebsite")
                        .HasColumnType("text")
                        .HasColumnName("startup_website");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CountryId" }, "IX_organization_settings_country_id");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_organization_settings_currency_id");

                    b.HasIndex(new[] { "StartupStageId" }, "IX_organization_settings_startup_stage_id");

                    b.ToTable("organization_settings");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.StartupStage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("startup_stages");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.StartupVertical", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("startup_verticals");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarUrl")
                        .HasColumnType("text")
                        .HasColumnName("calendar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XUrl")
                        .HasColumnType("text")
                        .HasColumnName("x_url");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("InvestorCountry", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestorStartupStage", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.StartupStage", null)
                        .WithMany()
                        .HasForeignKey("StartupStage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestorStartupVertical", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.StartupVertical", null)
                        .WithMany()
                        .HasForeignKey("StartupVerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_investor_startup_verticals_startup_vertical_startup_vertica~");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Contact", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Investor", "Investor")
                        .WithMany("Contacts")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Deal", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Contact", "Contact")
                        .WithMany("Deals")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.DealApproach", "DealApproach")
                        .WithMany("Deals")
                        .HasForeignKey("DealApproachId");

                    b.HasOne("Ivy.Open.Raise.Connections.Data.DealState", "DealState")
                        .WithMany("Deals")
                        .HasForeignKey("DealStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.User", "Owner")
                        .WithMany("Deals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("DealApproach");

                    b.Navigation("DealState");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckLink", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Contact", "Contact")
                        .WithMany("DeckLinks")
                        .HasForeignKey("ContactId");

                    b.HasOne("Ivy.Open.Raise.Connections.Data.Deck", "Deck")
                        .WithMany("DeckLinks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckLinkView", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.DeckLink", "DeckLink")
                        .WithMany("DeckLinkViews")
                        .HasForeignKey("DeckLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckLink");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckVersion", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Deck", "Deck")
                        .WithMany("DeckVersions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Interaction", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Contact", "Contact")
                        .WithMany("Interactions")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.InteractionType", "InteractionTypeNavigation")
                        .WithMany("Interactions")
                        .HasForeignKey("InteractionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.User", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("InteractionTypeNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Investor", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Country", "AddressCountry")
                        .WithMany("Investors")
                        .HasForeignKey("AddressCountryId");

                    b.HasOne("Ivy.Open.Raise.Connections.Data.InvestorType", "InvestorType")
                        .WithMany("Investors")
                        .HasForeignKey("InvestorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressCountry");

                    b.Navigation("InvestorType");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.OrganizationSetting", b =>
                {
                    b.HasOne("Ivy.Open.Raise.Connections.Data.Country", "Country")
                        .WithMany("OrganizationSettings")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.Currency", "Currency")
                        .WithMany("OrganizationSettings")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ivy.Open.Raise.Connections.Data.StartupStage", "StartupStage")
                        .WithMany("OrganizationSettings")
                        .HasForeignKey("StartupStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("StartupStage");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Contact", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("DeckLinks");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Country", b =>
                {
                    b.Navigation("Investors");

                    b.Navigation("OrganizationSettings");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Currency", b =>
                {
                    b.Navigation("OrganizationSettings");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DealApproach", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DealState", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Deck", b =>
                {
                    b.Navigation("DeckLinks");

                    b.Navigation("DeckVersions");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.DeckLink", b =>
                {
                    b.Navigation("DeckLinkViews");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.InteractionType", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.Investor", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.InvestorType", b =>
                {
                    b.Navigation("Investors");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.StartupStage", b =>
                {
                    b.Navigation("OrganizationSettings");
                });

            modelBuilder.Entity("Ivy.Open.Raise.Connections.Data.User", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Interactions");
                });
#pragma warning restore 612, 618
        }
    }
}
